// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwoOIXQuKBFkmlNMO18i9zvUTUcHETYgM',
    appId: '1:992774284598:web:c46cb2a445c34afe733f97',
    messagingSenderId: '992774284598',
    projectId: 'nightreaderpro',
    authDomain: 'nightreaderpro.firebaseapp.com',
    storageBucket: 'nightreaderpro.firebasestorage.app',
    measurementId: 'G-XVE1BTMY6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbFT2JVF4lvU6nKuqVS-Yo6qAvsdmbS5Y',
    appId: '1:992774284598:android:ab5c6d532334112e733f97',
    messagingSenderId: '992774284598',
    projectId: 'nightreaderpro',
    storageBucket: 'nightreaderpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDre14N0d6q90-_HI5tHEYoxWzx-3VUzek',
    appId: '1:992774284598:ios:55b2f3d0b478f253733f97',
    messagingSenderId: '992774284598',
    projectId: 'nightreaderpro',
    storageBucket: 'nightreaderpro.firebasestorage.app',
    iosBundleId: 'com.renga.nightreaderpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDre14N0d6q90-_HI5tHEYoxWzx-3VUzek',
    appId: '1:992774284598:ios:28440299bdafbed6733f97',
    messagingSenderId: '992774284598',
    projectId: 'nightreaderpro',
    storageBucket: 'nightreaderpro.firebasestorage.app',
    iosBundleId: 'com.example.nightreader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwoOIXQuKBFkmlNMO18i9zvUTUcHETYgM',
    appId: '1:992774284598:web:e2191e75489a4de9733f97',
    messagingSenderId: '992774284598',
    projectId: 'nightreaderpro',
    authDomain: 'nightreaderpro.firebaseapp.com',
    storageBucket: 'nightreaderpro.firebasestorage.app',
    measurementId: 'G-TEJC9QQJ8N',
  );
}
