// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE4cNiQhtNjF-EnoguXeWx8HsMVYKSndA',
    appId: '1:455131974505:web:144da7117653cf76044bf8',
    messagingSenderId: '455131974505',
    projectId: 'nightreader-3a2f8',
    authDomain: 'nightreader-3a2f8.firebaseapp.com',
    storageBucket: 'nightreader-3a2f8.firebasestorage.app',
    measurementId: 'G-SKNFGRJR20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7iQ8Lv8xHjbOZR8CQoBVV8WEGzPPsliI',
    appId: '1:455131974505:android:f4224b86a4dca6db044bf8',
    messagingSenderId: '455131974505',
    projectId: 'nightreader-3a2f8',
    storageBucket: 'nightreader-3a2f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMdPer3uo4WmT9-ZbBfivz0L54uOArM5M',
    appId: '1:455131974505:ios:ea93484cec65f77b044bf8',
    messagingSenderId: '455131974505',
    projectId: 'nightreader-3a2f8',
    storageBucket: 'nightreader-3a2f8.firebasestorage.app',
    iosBundleId: 'com.example.nightreader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMdPer3uo4WmT9-ZbBfivz0L54uOArM5M',
    appId: '1:455131974505:ios:ea93484cec65f77b044bf8',
    messagingSenderId: '455131974505',
    projectId: 'nightreader-3a2f8',
    storageBucket: 'nightreader-3a2f8.firebasestorage.app',
    iosBundleId: 'com.example.nightreader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE4cNiQhtNjF-EnoguXeWx8HsMVYKSndA',
    appId: '1:455131974505:web:d5547a19ed425d94044bf8',
    messagingSenderId: '455131974505',
    projectId: 'nightreader-3a2f8',
    authDomain: 'nightreader-3a2f8.firebaseapp.com',
    storageBucket: 'nightreader-3a2f8.firebasestorage.app',
    measurementId: 'G-F6NR0XFJF9',
  );
}
